# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blogging Time
email: meg@mcoyle.com
description: > # this means to ignore newlines until "baseurl:"
  A site for blogging about the odds and ends that come up in life.
# baseurl: "/blogging-time" # the subpath of your site, e.g. /blog
# url: "http://megancoyle.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: megancoyle
github_username:  megancoyle

# Build settings
markdown: kramdown
